services:
  flask:
    container_name: flask-website-flask
    build:
      context: ../                                            # must be parent; Dockerfile can't access parent dirs
      dockerfile: docker/flask/Dockerfile_flask               # SYNC: path
    env_file:                                                 # SYNC: env file paths
      - ./flask/envs/.env
      - ./flask/envs/.flaskenv
    ports:
      - "8008:8008"                                           # SYNC with Nginx and Gunicorn in entrypoint: ports
    volumes:
      - type: bind                                            # for persisting uploaded images in static folders
        source: ../app/blog/static/blog/blogpage/             # SYNC: path
        target: /flask-website/app/blog/static/blog/blogpage/ # SYNC with Dockerfile: path "/flask-website/"
    restart: always
  mysql:
    container_name: flask-website-mysql
    image: "mysql:8.0.37"                                     # SYNC: host's MySql version if using bind mount
    env_file:
      - ./mysql/envs/.mysqlenv                                # SYNC: env file paths
    volumes:
      - type: bind                                            # for persisting database
        source: /var/lib/mysql/
        target: /var/lib/mysql/
    restart: always
