services:
  flask:
    build:
      context: ../                                            # must be parent; Dockerfile can't access parent dirs
      dockerfile: docker/flask/Dockerfile_flask               # SYNC: path
    env_file:                                                 # SYNC: env file paths
      - ./flask/envs/.env
      - ./flask/envs/.flaskenv
    ports:
      - "8008:8008"                                           # SYNC with Nginx and Gunicorn in entrypoint: ports
    volumes:                                                  # for persisting uploaded images in static folders
      - type: bind
        source: ../app/blog/static/blog/blogpage/             # SYNC: path
        target: /flask-website/app/blog/static/blog/blogpage/ # SYNC with Dockerfile: path "/flask-website/"
    restart: always
  mysql:
    image: "mysql:8.0.37"
    env_file:
      - ./mysql/envs/.mysqlenv                                # SYNC: env file paths
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:                                                  # for persisting database
      - type: bind
        source: /var/lib/mysql/
        target: /var/lib/mysql/
    restart: always
